name: Cross Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-arm64:
    runs-on: ubuntu-latest
    env:
      CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      TARGET: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install Rust target
        run: rustup target add ${{ env.TARGET }}

      - name: Build
        run: cargo -vv build --release --locked --target ${{ env.TARGET }}
